.builder:
  stage: build
  image: 
    name: moby/buildkit:rootless
    entrypoint: [sh, -c]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - |
      mkdir -p ~/.docker && cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)"
          }
        }
      }
      EOF
    - |
      dockerbuild() {
        buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt filename=$1.Dockerfile \
          --output type=image,name=$CI_REGISTRY_IMAGE/$1:$2,push=true
      }

stages:
  - version
  - build

include:
  - go-just.gitlab-ci.yml
