.builder:
  stage: build
  image: moby/buildkit:rootless
  before_script:
    - |
      mkdir -p ~/.docker && cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)"
          }
        }
      }
      EOF
    - |
      dockerbuild() {
        buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=$0.Dockerfile \
          --output type=image,name=$CI_REGISTRY_IMAGE/$0:$1,push=true
      }

stages:
  - version
  - build

include:
  - go-just.gitlab-ci.yml
