go-just:
  extends: .builder
  rules: 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: [go-just.*, .gitlab-ci.yml]
  script:
    # get build go version from FROM statement
    - go_version=$(grep -Po '(?<=FROM golang:).*(?=-alpine)')
    - just_version=$(grep -Po '(?<=--tag ).*$')
    - echo Building image with Go $go_version and Just $just_version
    - dockerbuild go-just $go_version-$just_version
