go-just:
  extends: .builder
  rules: 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: [go-just.*, .gitlab-ci.yml]
  script:
    # get build go version from FROM statement
    - grep -Eo 'FROM golang:.*' go-just.Dockerfile | sed 's/FROM golang://' | sed s/-alpine//
    - grep -Eo '--tag .*$' go-just.Dockerfile | sed 's/--tag //'
    - echo Building image with Go $go_version and Just $just_version
    - dockerbuild go-just $go_version-$just_version
