go-just:
  extends: .builder
  rules: 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: [go-just.*]
  script:
    # get build go version from FROM statement
    - go_version=$(grep -Eo '^(?<=FROM golang:).*(?=-alpine)$')
    - just_version=$(grep -Eo '(?<=--tag ).*$')
    - echo Building image with Go $go_version and Just $just_version
    - dockerbuild go-just $go_version-$just_version
